import getMonthName from "./getMonthName";
import numeroParaExtenso from "./numeroParaExtenso";
import { IFormCaucaoData, IFormFiancaData } from "@/types/IFormData";

export const debugFiancaData: IFormFiancaData = {
  form_tipo: "fianca",
  nome_dono: "Carlos Alberto Pereira",
  rg_dono: "45.678.901-2",
  orgao_rg_dono: "SSP/MG",
  cpf_dono: "456.789.012-34",
  cep_dono: "30123-456",
  logradouro_dono: "Avenida Paulista",
  numero_dono: "1000",
  complemento_dono: "Sala 1501",
  bairro_dono: "Bela Vista",
  cidade_dono: "Belo Horizonte",
  estado_dono: "MG",

  nome_inquilino: "Ana Claudia Mendonça",
  rg_inquilino: "23.456.789-0",
  orgao_rg_inquilino: "SSP/RS",
  cpf_inquilino: "234.567.890-12",
  estado_civil: "Solteira",
  profissao: "Arquiteta",
  cep_inquilino: "90210-123",
  logradouro_inquilino: "Rua das Flores",
  numero_inquilino: "45",
  complemento_inquilino: "Bloco B",
  bairro_inquilino: "Moema",
  cidade_inquilino: "Porto Alegre",
  estado_inquilino: "RS",

  cep_imovel: "45678-901",
  logradouro_imovel: "Rua das Palmeiras",
  numero_imovel: "200",
  bairro_imovel: "Jardim América",
  cidade_imovel: "Curitiba",
  estado_imovel: "PR",

  dia_pagamento_aluguel: "10",
  dia_pagamento_escrito: numeroParaExtenso(10),
  numero_luz_enel: "9876543210",
  inicio_locacao: "2024-03-15",
  inicio_mes_locacao: getMonthName(3).toUpperCase(),
  fim_locacao: "2026-03-14",
  fim_mes_locacao: getMonthName(3).toUpperCase(),
  dia_assinatura: "20",
  mes_assinatura: "março",
  data_seguro_fianca: "2027-01-15",
  valor_aluguel: "2500",
  valor_aluguel_escrito: "Dois mil e quinhentos reais",
};

export const debugCaucaoData: IFormCaucaoData = {
  form_tipo: "caucao",
  nome_dono: "Fernanda Oliveira Costa",
  rg_dono: "34.567.890-1",
  orgao_rg_dono: "SSP/BA",
  cpf_dono: "345.678.901-23",
  cep_dono: "40000-000",
  logradouro_dono: "Avenida Sete de Setembro",
  numero_dono: "500",
  complemento_dono: "Conjunto 302",
  bairro_dono: "Barra",
  cidade_dono: "Salvador",
  estado_dono: "BA",

  nome_inquilino: "Ricardo Almeida Santos",
  rg_inquilino: "56.789.012-3",
  orgao_rg_inquilino: "SSP/PE",
  cpf_inquilino: "567.890.123-45",
  estado_civil: "Divorciado",
  profissao: "Advogado",
  cep_inquilino: "50000-123",
  logradouro_inquilino: "Rua do Sol",
  numero_inquilino: "300",
  complemento_inquilino: "Apto 1001",
  bairro_inquilino: "Boa Viagem",
  cidade_inquilino: "Recife",
  estado_inquilino: "PE",

  cep_imovel: "54321-098",
  logradouro_imovel: "Avenida Boa Vista",
  numero_imovel: "1500",
  complemento_imovel: "Andar 10",
  bairro_imovel: "Centro",
  cidade_imovel: "Fortaleza",
  estado_imovel: "CE",

  dia_pagamento_aluguel: "15",
  dia_pagamento_escrito: numeroParaExtenso(15),
  numero_luz_enel: "0123456789",
  inicio_locacao: "2024-06-01",
  inicio_mes_locacao: getMonthName(6).toUpperCase(),
  fim_locacao: "2026-05-31",
  fim_mes_locacao: getMonthName(5).toUpperCase(),
  data_seguro_caucao: "2027-03-10",
  valor_caucao: "6000",
  valor_caucao_escrito: "Seis mil reais",
  valor_aluguel: "3000",
  valor_aluguel_escrito: "Três mil reais",
  data_assinatura: "2024-06-25",
};
