import getMonthName from "./getMonthName";
import numeroParaExtenso from "./numeroParaExtenso";
import { IFormFiancaData } from "@/types/IFormData";

export const debugFiancaData: IFormFiancaData = {
  nome_dono: "João Silva Santos",
  rg_dono: "12.345.678-9",
  orgao_rg_dono: "SSP/SP",
  cpf_dono: "123.456.789-00",
  cep_dono: "01234-567",
  logradouro_dono: "Rua Teste",
  numero_dono: "123",
  complemento_dono: "Apto 456",
  bairro_dono: "Centro",
  cidade_dono: "São Paulo",
  estado_dono: "SP",

  nome_inquilino: "Maria Oliveira Souza",
  rg_inquilino: "98.765.432-1",
  orgao_rg_inquilino: "SSP/RJ",
  cpf_inquilino: "987.654.321-00",
  estado_civil: "Casado",
  profissao: "Engenheira Civil",
  cep_inquilino: "98765-432",
  logradouro_inquilino: "Avenida Brasil",
  numero_inquilino: "789",
  complemento_inquilino: "Casa 2",
  bairro_inquilino: "Jardim das Flores",
  cidade_inquilino: "Campinas",
  estado_inquilino: "SP",

  cep_imovel: "12345-678",
  logradouro_imovel: "Avenida Principal",
  numero_imovel: "123",
  bairro_imovel: "Jardim das Flores",
  cidade_imovel: "Campinas",
  estado_imovel: "SP",

  dia_pagamento_aluguel: "5",
  dia_pagamento_escrito: numeroParaExtenso(5),
  numero_luz_enel: "1234567890",
  inicio_locacao: "2024-01-01",
  inicio_mes_locacao: getMonthName(1).toUpperCase(),
  fim_locacao: "2025-12-31",
  fim_mes_locacao: getMonthName(12).toUpperCase(),
  dia_assinatura: "15",
  mes_assinatura: "janeiro",
  data_seguro_fianca: "2026-06-27",
  valor_aluguel: "1500",
  valor_aluguel_escrito: "Mil e quinhentos reais",
};
